[platformio]
default_envs = esp8266
extra_configs = platformio.local.ini

[common]
build_flags =
  -I libraries/SimpleTimer
  -I libraries/NtpTime
  -I libraries/Misc

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_extra_dirs = libraries
build_src_filter =
  +<main.cpp>
lib_deps =
  knolleary/PubSubClient@^2.8
  paulstoffregen/Time@^1.6.1
build_flags = ${common.build_flags}
